# Generated by Django 6.0.1 on 2026-02-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to download app or visit website'),
        ),
        migrations.AddField(
            model_name='listing',
            name='how_it_works',
            field=models.TextField(blank=True, help_text='Detailed explanation of how the app/service works'),
        ),
        migrations.AddField(
            model_name='listing',
            name='logo',
            field=models.ImageField(blank=True, help_text='App icon or logo', null=True, upload_to='listings/logos/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to a demo video (e.g., YouTube)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Main cover image', null=True, upload_to='listings/'),
        ),
        migrations.CreateModel(
            name='ListingScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='listings.listing')),
            ],
        ),
    ]
