# Generated by Django 6.0.1 on 2026-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_external_link_listing_how_it_works_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Upload APK file for direct download', null=True, upload_to='listings/apks/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.TextField(blank=True, help_text='Key features (one per line)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD (0 for free)', max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
